### ISSUE TITLE
Could you tell me how I can install this tool in Térmux? please, I really need the tool😔

### ISSUE THREAD

**Issue by francivvaldo** [elliottophellia/TikTodRIP#3]
Could you tell me how I can install this tool in Térmux? please, I really need the tool

**Comment by elliottophellia** [comment]
```
pkg install python git
git clone https://github.com/elliottophellia/TikTodRIP
cd TikTodRIP
pip install -r requirements.txt
python  main.py
```

I think you should read readme.md before opening issues

**Comment by francivvaldo** [comment]
every time I put the cd tiktodRIP it says "No such file or directory" I can't install it😕
